### ISSUE TITLE
Fatal error in getListingsRestrictions method

### ISSUE THREAD

**Issue by crazybee47** [jlevers/selling-partner-api#194]
My code:
```
$api      = new \SellingPartnerApi\Api\ListingsRestrictionsApi($this->apiConfig());
$response = $api->getListingsRestrictions('B07VD9RQ73', 'A2ZDIUB7NOVCMO', [$marketplaceId], 'New');
```

Trace:
```
[previous exception] [object] (InvalidArgumentException(code: 0): Invalid array '\\SellingPartnerApi\\Model\\ListingsRestrictions\\Error[]' at /var/www/html/vendor/jlevers/selling-partner-api/lib/ObjectSerializer.php:270)
[stacktrace]
#0 /var/www/html/vendor/jlevers/selling-partner-api/lib/Api/ListingsRestrictionsApi.php(289): SellingPartnerApi\\ObjectSerializer::deserialize(Object(stdClass), '\\\\SellingPartner...', Array)
#1 /var/www/html/vendor/jlevers/selling-partner-api/lib/Api/ListingsRestrictionsApi.php(129): SellingPartnerApi\\Api\\ListingsRestrictionsApi->getListingsRestrictionsWithHttpInfo('B07VD9RQ73', 'A2ZDIUB7NOVCMO', Array, 'New', NULL)
#2 /var/www/html/app/Service/Integration/Engine/Amazon/Api.php(336): SellingPartnerApi\\Api\\ListingsRestrictionsApi->getListingsRestrictions('B07VD9RQ73', 'A2ZDIUB7NOVCMO', Array, 'New')
#3 /var/www/html/app/Service/Integration/Engine/Amazon/Api.php(370): App\\Service\\Integration\\Engine\\Amazon\\Api->App\\Service\\Integration\\Engine\\Amazon\\{closure}()
#4 /var/www/html/app/Service/Integration/Engine/Amazon/Api.php(341): App\\Service\\Integration\\Engine\\Amazon\\Api->execute(Object(Closure))
#5 /var/www/html/app/Service/Integration/Engine/Amazon/Application.php(160): App\\Service\\Integration\\Engine\\Amazon\\Api->createInventory('ATVPDKIKX0DER')
#6 /var/www/html/app/Service/Integration/IntegrationManager.php(281): App\\Service\\Integration\\Engine\\Amazon\\Application->createInventory(Array)
#7 /var/www/html/app/Service/Integration/IntegrationManager.php(327): App\\Service\\Integration\\IntegrationManager->App\\Service\\Integration\\{closure}(Object(App\\Service\\Integration\\Engine\\Amazon\\Application))
#8 /var/www/html/app/Service/Integration/IntegrationManager.php(279): App\\Service\\Integration\\IntegrationManager->execute(Object(Closure), Object(App\\Models\\Project\\Integration))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): App\\Service\\Integration\\IntegrationManager->createInventory(Object(App\\Models\\Project\\Integration))
#10 /var/www/html/app/Service/Integration/IntegrationFacade.php(30): Illuminate\\Support\\Facades\\Facade::__callStatic('createInventory', Array)
#11 /var/www/html/test.php(33): App\\Service\\Integration\\IntegrationFacade::__callStatic('createInventory', Array)
#12 {main}
"} 
```

In response body i got:
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Request has missing or invalid parameters and cannot be parsed.",
      "details": ""
    }
  ]
}
```

**Comment by crazybee47** [comment]
I realized what my problem was, you need to specify enum values as condition Type (https://github.com/amzn/selling-partner-api-docs/blob/main/references/listings-restrictions-api/listingsRestrictions_2021-08-01.md#conditiontype-subgroup-1)
