### ISSUE TITLE
Errors in Authentication.php

### ISSUE THREAD

**Issue by tazplan** [jlevers/selling-partner-api#195]
Hello,

I just tried to run on my webserver for testing, I got 2 errors. Here the first:

PHP Parse error:  syntax error, unexpected ')' in selling-partner-api-main/lib/Authentication.php on line 280

After removing the coma on line 280, I got the next error:

PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\Client' not found in selling-partner-api-main/lib/Authentication.php:59
Stack trace:
#0 selling-partner-api-main/lib/Configuration.php(117): SellingPartnerApi\Authentication->__construct(Array)
#1 spapi-test.php(19): SellingPartnerApi\Configuration->__construct(Array)
#2 {main}
  thrown in selling-partner-api-main/lib/Authentication.php on line 59
[05-Feb-2022 15:32:48 UTC] PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\Client' not found in selling-partner-api-main/lib/Authentication.php:59
Stack trace:
#0 selling-partner-api-main/lib/Configuration.php(117): SellingPartnerApi\Authentication->__construct(Array)
#1 spapi-test.php(19): SellingPartnerApi\Configuration->__construct(Array)
#2 {main}
  thrown in selling-partner-api-main/lib/Authentication.php on line 59

 Any idea how to solve the GuzzleHttp error?

**Comment by tazplan** [comment]
Not related, it is my php version outdated.
