### ISSUE TITLE
Unable to catch InvalidArgumentException exception

### ISSUE THREAD

**Issue by ali-cedcoss** [jlevers/selling-partner-api#357]
## Problem description:

Hi, I am using the SDK in AWS Lambda invoked through AWS API Gateway. To test out my code for better error handling, I gave it a wrong marketplace ID which in turn throws InvalidArgumentException but my php code on Lambda is unable to catch this. Any other Amazon API errors from the SDK are being successfully returned but I am unable to catch the InvalidArgumentException.

## Error:

```

"errorType":"InvalidArgumentException","errorMessage":"Unknown marketplace ID \"A1F83G8C2AO7P\".","stack":["#0 \/var\/task\/amz_get_inventory_summary.php(52): SellingPartnerApi\\Endpoint::getByMarketplaceId()","#1 \/var\/task\/vendor\/bref\/bref\/src\/Event\/Http\/Psr15Handler.php(22): HttpHandler->handle()","#2 \/var\/task\/vendor\/bref\/bref\/src\/Event\/Http\/HttpHandler.php(25): Bref\\Event\\Http\\Psr15Handler->handleRequest()","#3 \/var\/task\/vendor\/bref\/bref\/src\/Runtime\/Invoker.php(29): Bref\\Event\\Http\\HttpHandler->handle()","#4 \/var\/task\/vendor\/bref\/bref\/src\/Runtime\/LambdaRuntime.php(91): Bref\\Runtime\\Invoker->invoke()","#5 \/opt\/bref\/bootstrap.php(43): Bref\\Runtime\\LambdaRuntime->processNextEvent()","#6 {main}"]}
```

## Code

```php
try {
    $apiInstance = new FbaInventoryApi($config);
    $result = $apiInstance->getInventorySummaries('Marketplace', $marketplace_id, $marketplace_id_arr, 'true');
    $return_json = json_encode($result->jsonSerialize(), true);
    var_dump($result);
} catch (Exception $e) {
    $return_json = json_encode([
        'success' => 'false',
        'body' => json_encode($e->getMessage())
    ]);
    return new Response(200, ['Content-Type' => 'application/json'], $return_json);
}
```

## Seller Central SP API config page screenshot

**Comment by jlevers** [comment]
I don't know what might be causing this but I'm guessing it's related to the Lambda rather than the library. I'm not sure how the library would be failing to throw this error. That said, if you have some reason to believe this *is* a problem with the library, let me know and I'll try to address it.
