### ISSUE TITLE
Errors with patchListings

### ISSUE THREAD

**Issue by nikgilbe** [jlevers/selling-partner-api#363]
## Problem description:
Hi - I've just been attempting to update stock quantity via the API, and am getting the error below - all other APIs working as expected. 

## Error:
```
PHP Fatal error:  Uncaught SellingPartnerApi\ApiException: [400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Value is missing for patch at index of 0.",
      "details": ""
    }
  ]
} in /aws/bin/vendor/jlevers/selling-partner-api/lib/Api/ListingsApi.php:1056
Stack trace:
#0 /aws/bin/vendor/jlevers/selling-partner-api/lib/Api/ListingsApi.php(1018): SellingPartnerApi\Api\ListingsApi->patchListingsItemWithHttpInfo()
#1 /aws/bin/afiCheckActive.php(60): SellingPartnerApi\Api\ListingsApi->patchListingsItem()
#2 {main}
  thrown in /aws/bin/vendor/jlevers/selling-partner-api/lib/Api/ListingsApi.php on line 1056

Fatal error: Uncaught SellingPartnerApi\ApiException: [400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Value is missing for patch at index of 0.",
      "details": ""
    }
  ]
} in /aws/bin/vendor/jlevers/selling-partner-api/lib/Api/ListingsApi.php:1056
Stack trace:
#0 /aws/bin/vendor/jlevers/selling-partner-api/lib/Api/ListingsApi.php(1018): SellingPartnerApi\Api\ListingsApi->patchListingsItemWithHttpInfo()
#1 /aws/bin/afiCheckActive.php(60): SellingPartnerApi\Api\ListingsApi->patchListingsItem()
#2 {main}
  thrown in /aws/bin/vendor/jlevers/selling-partner-api/lib/Api/ListingsApi.php on line 1056
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
$data = [
        "productType" => "PRODUCT",
        "patches" => [
                new \SellingPartnerApi\Model\Listings\PatchOperation([
                        "op" => "replace",
                        "path" => "/attributes/fulfillment_availability",
                        "value" => [
                                "quantity" => 5,
                                "fulfillment_channel_code" => "DEFAULT"
                        ]
                ])
        ]
];
$result = $patchApi->patchListingsItem($seller_id, 'ABC123456', $marketplace_ids, $data, $issue_locale);
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
`value` needs to be an array of arrays. Try this:

```php
$data = [
        "productType" => "PRODUCT",
        "patches" => [
                new \SellingPartnerApi\Model\Listings\PatchOperation([
                        "op" => "replace",
                        "path" => "/attributes/fulfillment_availability",
                        "value" => [
                            [
                                "quantity" => 5,
                                "fulfillment_channel_code" => "DEFAULT"
                            ]
                        ]
                ])
        ]
];
$result = $patchApi->patchListingsItem($seller_id, 'ABC123456', $marketplace_ids, $data, $issue_locale);
```

**Comment by nikgilbe** [comment]
Thanks so much as always :-) 

I was staring at that blankly for ages.
