### ISSUE TITLE
Please define apiRequestException

### ISSUE THREAD

**Issue by soseki-angfa** [jlevers/selling-partner-api#447]
Hello sir,

I am getting error when I updated to v5.5.0
I am getting an error from your library.
So, please check this out.

```
PHP Fatal error:  Uncaught Error: Class 'SellingPartnerApi\Api\ApiException' not found in /home/maint/batch/amazon-sp-api/vendor/jlevers/selling-partner-api/lib/Api/SellersV1Api.php:85
Stack trace:
#0 /home/maint/batch/amazon-sp-api/vendor/jlevers/selling-partner-api/lib/Api/SellersV1Api.php(52): SellingPartnerApi\Api\SellersV1Api->getMarketplaceParticipationsWithHttpInfo()
#1 /home/maint/batch/amazon-sp-api/app.php(23): SellingPartnerApi\Api\SellersV1Api->getMarketplaceParticipations()
#2 {main}
  thrown in /home/maint/batch/amazon-sp-api/vendor/jlevers/selling-partner-api/lib/Api/SellersV1Api.php on line 85
```

**Comment by steverobison** [comment]
Here is my response from a similar issue (#445).  That is a quick hack that will work until the developer updates the api generator with the complete fix.

https://github.com/jlevers/selling-partner-api/issues/445#issuecomment-1357773533
