### ISSUE TITLE
Getting the exception on CatalogItemsV20220401Api.php while the same code works for catalog categories

### ISSUE THREAD

**Issue by ehtisham-mustafa9** [jlevers/selling-partner-api#451]
## Problem description:
[2022-12-22 09:07:11] local.INFO: API Exception => SellingPartnerApi\Api\ApiException: [404] {
  "errors": [
    {
      "code": "NOT_FOUND",
      "message": "Requested item, B076VX8RC5, not found in marketplace(s) ATVPDKIKX0DER."
    }
  ]

## Error:
Requested asin not found in the marketplace.
```
# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
Not sure if this is what's causing the error, but `ATVPDKIKX0DEW` is not a valid marketplace ID. The marketplace ID for the US is `ATVPDKIKX0DER`.

**Comment by ehtisham-mustafa9** [comment]
[2022-12-23 18:30:05] local.INFO: Getting Items from getCatalogItem API for Asin B076VX8RC5  MarketplaceId ATVPDKIKX0DER  
[2022-12-23 18:30:09] local.INFO: Error in API => 404 , Uploading dummy data  [{"asin":"B076VX8RC5","marketplaceId":"ATVPDKIKX0DER"}]  
[2022-12-23 18:30:09] local.INFO: API Exception => SellingPartnerApi\Api\ApiException: [404] {
  "errors": [
    {
      "code": "NOT_FOUND",
      "message": "Requested item, B076VX8RC5, not found in marketplace(s) ATVPDKIKX0DER."
    }
  ]
} in /home/vagrant/code/capx-multi-channel/app/Capx/SellingPartnerApiMain/lib/Api/CatalogItemsV20220401Api.php:93
Stack trace:
#0 /home/vagrant/code/capx-multi-channel/app/Capx/SellingPartnerApiMain/lib/Api/CatalogItemsV20220401Api.php(56): SellingPartnerApi\Api\CatalogItemsV20220401Api->getCatalogItemWithHttpInfo()
#1 /home/vagrant/code/capx-multi-channel/app/Jobs/Catalog/Item/SyncCatalogItemsJob.php(155): SellingPartnerApi\Api\CatalogItemsV20220401Api->getCatalogItem()
#2 /home/vagrant/code/capx-multi-channel/app/Jobs/Catalog/Item/SyncCatalogItemsJob.php(64): App\Jobs\Catalog\Item\SyncCatalogItemsJob->_getApiResponse()
#3 [internal function]: App\Jobs\Catalog\Item\SyncCatalogItemsJob->handle()
#4 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#5 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod()
#7 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call()
#8 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#9 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#10 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#12 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow()
#13 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call()
#14 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#15 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process()
#16 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob()
#17 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon()
#18 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker()
#19 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#20 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#21 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod()
#23 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call()
#24 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call()
#25 /home/vagrant/code/capx-multi-channel/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#26 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run()
#27 /home/vagrant/code/capx-multi-channel/vendor/symfony/console/Application.php(1021): Illuminate\Console\Command->run()
#28 /home/vagrant/code/capx-multi-channel/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#29 /home/vagrant/code/capx-multi-channel/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#30 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run()
#31 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run()
#32 /home/vagrant/code/capx-multi-channel/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#33 {main}  
[2022-12-23 18:30:09] local.INFO: Uploading to S3 /home/vagrant/code/capx-multi-channel/public/uploads/20221223183009_1671849009_8032_B076VX8RC5.json -> capx-ams-local/catalog/items/marketplaceId=ATVPDKIKX0DER/B076VX8RC5.json  
[2022-12-23 18:30:11] local.INFO: File successfully uploaded to s3 => status 1

**Comment by ehtisham-mustafa9** [comment]
> Not sure if this is what's causing the error, but `ATVPDKIKX0DEW` is not a valid marketplace ID. The marketplace ID for the US is `ATVPDKIKX0DER`.

here is the complete error in catalog items
[2022-12-23 18:30:05] local.INFO: Getting Items from getCatalogItem API for Asin B076VX8RC5  MarketplaceId ATVPDKIKX0DER  
[2022-12-23 18:30:09] local.INFO: Error in API => 404 , Uploading dummy data  [{"asin":"B076VX8RC5","marketplaceId":"ATVPDKIKX0DER"}]  
[2022-12-23 18:30:09] local.INFO: API Exception => SellingPartnerApi\Api\ApiException: [404] {
  "errors": [
    {
      "code": "NOT_FOUND",
      "message": "Requested item, B076VX8RC5, not found in marketplace(s) ATVPDKIKX0DER."
    }
  ]
} in /home/vagrant/code/capx-multi-channel/app/Capx/SellingPartnerApiMain/lib/Api/CatalogItemsV20220401Api.php:93
Stack trace:
#0 /home/vagrant/code/capx-multi-channel/app/Capx/SellingPartnerApiMain/lib/Api/CatalogItemsV20220401Api.php(56): SellingPartnerApi\Api\CatalogItemsV20220401Api->getCatalogItemWithHttpInfo()
#1 /home/vagrant/code/capx-multi-channel/app/Jobs/Catalog/Item/SyncCatalogItemsJob.php(155): SellingPartnerApi\Api\CatalogItemsV20220401Api->getCatalogItem()
#2 /home/vagrant/code/capx-multi-channel/app/Jobs/Catalog/Item/SyncCatalogItemsJob.php(64): App\Jobs\Catalog\Item\SyncCatalogItemsJob->_getApiResponse()
#3 [internal function]: App\Jobs\Catalog\Item\SyncCatalogItemsJob->handle()
#4 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#5 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod()
#7 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call()
#8 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#9 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#10 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#12 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow()
#13 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call()
#14 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#15 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker->process()
#16 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob()
#17 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon()
#18 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker()
#19 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#20 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#21 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod()
#23 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\Container\BoundMethod::call()
#24 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call()
#25 /home/vagrant/code/capx-multi-channel/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#26 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run()
#27 /home/vagrant/code/capx-multi-channel/vendor/symfony/console/Application.php(1021): Illuminate\Console\Command->run()
#28 /home/vagrant/code/capx-multi-channel/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#29 /home/vagrant/code/capx-multi-channel/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#30 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run()
#31 /home/vagrant/code/capx-multi-channel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run()
#32 /home/vagrant/code/capx-multi-channel/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#33 {main}  
[2022-12-23 18:30:09] local.INFO: Uploading to S3 /home/vagrant/code/capx-multi-channel/public/uploads/20221223183009_1671849009_8032_B076VX8RC5.json -> capx-ams-local/catalog/items/marketplaceId=ATVPDKIKX0DER/B076VX8RC5.json  
[2022-12-23 18:30:11] local.INFO: File successfully uploaded to s3 => status 1

**Comment by ehtisham-mustafa9** [comment]
> Not sure if this is what's causing the error, but `ATVPDKIKX0DEW` is not a valid marketplace ID. The marketplace ID for the US is `ATVPDKIKX0DER`.

I have given the valid marketplace id now please can you check this 
[2022-12-23 18:30:05] local.INFO: Getting Items from getCatalogItem API for Asin B076VX8RC5  MarketplaceId ATVPDKIKX0DER  
[2022-12-23 18:30:09] local.INFO: Error in API => 404 , Uploading dummy data  [{"asin":"B076VX8RC5","marketplaceId":"ATVPDKIKX0DER"}]  
[2022-12-23 18:30:09] local.INFO: API Exception => SellingPartnerApi\Api\ApiException: [404] {
  "errors": [
    {
      "code": "NOT_FOUND",
      "message": "Requested item, B076VX8RC5, not found in marketplace(s) ATVPDKIKX0DER."
    }
  ]
} in /home/vagrant/codeSellingPartnerApiMain/lib/Api/CatalogItemsV20220401Api.php:93
Stack trace:
#0 /home/vagrant/codeSellingPartnerApiMain/lib/Api/CatalogItemsV20220401Api.php(56): SellingPartnerApi\Api\CatalogItemsV20220401Api->getCatalogItemWithHttpInfo()
#1 /home/vagrant/app/Jobs/Catalog/Item/SyncCatalogItemsJob.php(155):

**Comment by jlevers** [comment]
The product that you're looking for doesn't exist in the US marketplace. I just checked by going to https://www.amazon.com/dp/B076VX8RC5, which brings me to a 404 page. That ASIN belongs to a different marketplace.

**Comment by sunil11475-dev** [comment]
Hi, I have uploaded this new CatalogItemsV20220401Api files, now I am getting this message - Please help - 

Exception when calling CatalogItemsV2Api->getCatalogItem: [403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }

But works perfectly with CatalogItemsV0Api.php API Model files.

**Comment by jlevers** [comment]
Closing due to inactivity.
