### ISSUE TITLE
If fields are of type DateTime, their value should be null if they cannot be parsed

### ISSUE THREAD

**Issue by thinh-intersoft** [jlevers/selling-partner-api#758]
Version: 7.0.4
## Error:

```
[2024-07-16 03:22:59] local.ERROR: FBA Inventory Job import failed! {"code":0,"reason":"[object] (SellingPartnerApi\\Exceptions\\UnknownDatetimeFormatException(code: 0): The value `` uses a unknown DateTime format. at /home/vagrant/code/datadash-saas/vendor/jlevers/selling-partner-api/src/Traits/Deserializes.php:142)
[stacktrace]
#0 /home/vagrant/code/datadash-saas/vendor/jlevers/selling-partner-api/src/Traits/Deserializes.php(99): SellingPartnerApi\\Dto::convertValueToDateTime()
#1 /home/vagrant/code/datadash-saas/vendor/jlevers/selling-partner-api/src/Traits/Deserializes.php(71): SellingPartnerApi\\Dto::deserializeValue()
...
```

## Code

```php
    public function getInventorySummaries(
        string     $granularityType,
        string     $granularityId,
        array      $marketplaceIds,
        ?string    $details = null,
        ?\DateTime $startDateTime = null,
        ?array     $sellerSkus = null,
        ?string    $sellerSku = null,
        ?string    $nextToken = null,
    )
    {
        $response = $this->connector->fbaInventoryV1()->getInventorySummaries(
            granularityType: $granularityType,
            granularityId: $granularityId,
            marketplaceIds: $marketplaceIds,
            details: $details,
            startDateTime: $startDateTime,
            sellerSkus: $sellerSkus,
            sellerSku: $sellerSku,
            nextToken: $nextToken
        );

        return $response->dto();
    }
```

## Seller Central SP API config page screenshot

Working with $response->array() normally

## Reason

Can not parse with value: "", false,...

**Comment by jlevers** [comment]
The thing about this is that we'll never know if there are unsupported datetime formats being sent by Amazon if we don't throw an exception when they arise. I understand that it would be easier in some cases if you didn't hit an exception, but given that you can call `$response->json()` to avoid the exception if need be, I'm going to continue throwing the exception.
