### ISSUE TITLE
Call to a member function toArray() on array

### ISSUE THREAD

**Issue by TonyMarston** [jlevers/selling-partner-api#783]
## Error:

```
Uncaught exception from Error, message = Call to a member function toArray() on array, code=0, file=F:\Apache2\HTDOCS\GMX-Transix\includes\vendor\jlevers\selling-partner-api\src\Traits\HasArrayableAttributes.php, line=68
```

## Code

```php
require_once('vendor/autoload.php');
use SellingPartnerApi\SellingPartnerApi;
use SellingPartnerApi\Enums\Endpoint;
use SellingPartnerApi\Seller\APlusContentV20201101\Dto;

$connector = SellingPartnerApi::seller(
    clientId: $client_id,
    clientSecret: $client_secret,
    refreshToken: $refresh_token,
    endpoint: Endpoint::{$endpoint}
);

$api = $connector->aPlusContentV20201101();

try {
    $result = $api->validateContentDocumentAsinRelations(
        marketplaceId: $marketplace_id,
        postContentDocumentRequest: new Dto\PostContentDocumentRequest(new Dto\ContentDocument($name,
                                                                                               $contentType,
                                                                                               $locale,
                                                                                               $contentModuleList,
                                                                                               $contentSubType)));
} catch (Exception $e) {
    echo 'Exception when calling aPlusContentV20201101->validateContentDocumentAsinRelations: ',
        $e->getMessage(),
        PHP_EOL;
};
```
The code appears to fail when processing the $contentModuleList argument, but as this is already an array why is it failing?

**Comment by a-diessner** [comment]
I'm in similar problems. Have you found a solution?

**Comment by SamHeijder2002** [comment]
I have the same problem, is there a fix yet?

**Comment by TonyMarston** [comment]
I have had no response to this issue at all. I did raise another issue (https://github.com/jlevers/selling-partner-api/issues/819) complaining about the quality of his documentation, particularly a missing “use” statement, but he claimed it was my fault for not knowing how to use his library. I no longer have any confidence in the quality of his code so I have given up any idea of using it in my application. 
 
Tony Marston
 
 <http://www.tonymarston.net> http://www.tonymarston.net
 <http://www.radicore.org> http://www.radicore.org

**Comment by GWTorstenDEV** [comment]
Hi,

to correct the error message "..Uncaught Error: Call to a member function toArray() on array.."

The PHP Script "HasArrayableAttributes.php has the following Code that causes the problem.

**exchange this Line of code:** `return $value->toArray();`
**with this:** `return (is_array($value)) ? $value : $value->toArray();`

With this correction the function `toArray` becomes only obejcts and not arrays anymore.

@jlevers pls implement this. thx

Remember when you Update the Plugin via composer the changes will be overwritten.

Greets
Torsten

**Comment by jlevers** [comment]
I can't reproduce this one. Here's the code I'm using:


```php
use SellingPartnerApi\Seller\APlusContentV20201101\Dto;

// set up API connection...

$api = $connector->aPlusContentV20201101();
$res = $api->validateContentDocumentAsinRelations(
    marketplaceId: 'ATVPDKIKX0DER',
    postContentDocumentRequest: new Dto\PostContentDocumentRequest(new Dto\ContentDocument(
        '<NAME>',
        'EBC',
        'en_US',
        [
            new Dto\ContentModule('STANDARD_COMPANY_LOGO')
        ],
    ))
);
```

@GWTorstenDEV could you share some code (with actual values in it) that triggers this problem? Thanks :)

**Comment by GWTorstenDEV** [comment]
Hi,

sry for the delayed answer.

The Problem i mentiod comes from Line 68 the from PHP Skript HasArrayableAttributes.php.

The line `return $value->toArray();`  fails with "Fatal error: Uncaught Error: Call to a member function toArray() on array..." or "Fatal error: Uncaught Error: Call to a member function toArray() on string" etc.

The above mention fix from me is not correct it must be the following:

`return (!is_object($value)) ? $value : $value->toArray();`

pls implement this. thx

for your request: (Note: sensible Data corrected)

Code example call patchListingsItem (Stock Update)

```
use SellingPartnerApi\SellingPartnerApi;
use SellingPartnerApi\Enums\Endpoint;
use SellingPartnerApi\Authentication\AccessTokenAuthenticator;
use SellingPartnerApi\Contracts\TokenCache;

$apiInstance = $sellerConnector->ListingsItemsV20210801();

$seller_id = 'XXX';
$sku = 'SKU-1';
$marketplace_ids = ['A1PA6795UKMFR9'];
$included_data = ['issues'];
$mode = null;
$issue_locale = 'de_DE';

$data = [
	"op" => "replace",
	"path" => "/attributes/fulfillment_availability",
	"value" => [
		[
			"fulfillment_channel_code" => "DEFAULT",
			"quantity" => 0
		]
	]
];

$body = new \SellingPartnerApi\Seller\ListingsItemsV20210801\Dto\ListingsItemPatchRequest('PRODUCT', $data);

$result = $apiInstance->patchListingsItem($seller_id, $sku, $body, $marketplace_ids, $included_data, $mode, $issue_locale)->json();

print_r($result);
```

Response: (without fix)

`Fatal error: Uncaught Error: Call to a member function toArray() on array`

Response (with fix)

```
Array
(
    [sku] => SKU-1
    [status] => ACCEPTED
    [submissionId] => xxxxxx
    [issues] => Array
        (
        )

)
```

I'll hope you understand me now.

Greets
Torsten

**Comment by jlevers** [comment]
The reason I keep asking questions about this issue without implementing the fix you've suggested is that I just can't figure out why I'm not getting the error, and other people are...so I can't write a test to ensure it stays fixed until I can reproduce it. 

Could you re-run the above example after calling `$sellerConnector->debug()`, and then share the full debug output and the full stack trace from the error?

**Comment by GWTorstenDEV** [comment]
Hi,

(Note: sensible Data corrected)

with `$sellerConnector->debug()` activated the output is still the same. The script crashes with Fatal Error:

`Fatal error: Uncaught Error: Call to a member function toArray() on array in /xxx/yyy/vendor/jlevers/selling-partner-api/src/Traits/HasArrayableAttributes.php:68 Stack trace: #0 /xxx/yyy/vendor/jlevers/selling-partner-api/src/Traits/HasArrayableAttributes.php(80): SellingPartnerApi\Dto->valueToArray() #1 /xxx/yyy/vendor/jlevers/selling-partner-api/src/Traits/HasArrayableAttributes.php(48): SellingPartnerApi\Dto->valueToArray() #2 /xxx/yyy/vendor/jlevers/selling-partner-api/src/Seller/ListingsItemsV20210801/Requests/PatchListingsItem.php(70): SellingPartnerApi\Dto->toArray() #3 /xxx/yyy/vendor/saloonphp/saloon/src/Traits/Body/HasJsonBody.php(32): SellingPartnerApi\Seller\ListingsItemsV20210801\Requests\PatchListingsItem->defaultBody() #4 /xxx/yyy/vendor/saloonphp/saloon/src/Http/PendingRequest/MergeBody.php(26): SellingPartnerApi\Seller\ListingsItemsV20210801\Requests\PatchListingsItem->body() #5 /xxx/yyy/vendor/saloonphp/saloon/src/Http/PendingRequest.php(315): Saloon\Http\PendingRequest\MergeBody->__invoke() #6 /xxx/yyy/vendor/saloonphp/saloon/src/Http/PendingRequest.php(113): Saloon\Http\PendingRequest->tap() #7 /xxx/yyy/vendor/saloonphp/saloon/src/Traits/Connector/SendsRequests.php(181): Saloon\Http\PendingRequest->__construct() #8 /xxx/yyy/vendor/saloonphp/saloon/src/Traits/Connector/SendsRequests.php(65): Saloon\Http\Connector->createPendingRequest() #9 /xxx/yyy/vendor/jlevers/selling-partner-api/src/Seller/ListingsItemsV20210801/Api.php(96): Saloon\Http\Connector->send() ... require_once('...') #15 {main} thrown in /xxx/yyy/vendor/jlevers/selling-partner-api/src/Traits/HasArrayableAttributes.php on line 68`

with the modified `HasArrayableAttributes.php` it gave me the following:

```
Saloon Request (PatchListingsItem) -> array:6 [▼
  "connector" => "SellingPartnerApi\Seller\SellerConnector"
  "request" => "SellingPartnerApi\Seller\ListingsItemsV20210801\Requests\PatchListingsItem"
  "method" => "PATCH"
  "uri" => "https://sellingpartnerapi-eu.amazon.com/listings/2021-08-01/items/A2UOMPE9HKOQ0W/SKU-1?marketplaceIds=A1PA6795UKMFR9&includedData=issues&issueLocale=de_DE"
  "headers" => array:6 [▶]
  "body" => "{"productType":"PRODUCT","patches":[{"op":"replace","path":"\/attributes\/fulfillment_availability","value":[{"fulfillment_channel_code":"DEFAULT","quantity":0}]}]} ◀"
]

Saloon Response (PatchListingsItem) -> array:3 [▼
  "status" => 200
  "headers" => array:12 [▶]
  "body" => """
    


      {"sku":"SKU-1","status":"ACCEPTED","submissionId":"xyz","issues":[]}


    """
]

Array
(
    [sku] => SKU-1
    [status] => ACCEPTED
    [submissionId] => xyz
    [issues] => Array
        (
        )

)
```

Greets
Torsten

**Comment by jlevers** [comment]
I cannot for the life of me figure out why you're getting this error and I'm not, with exactly the same data. It should be, that when you hit an attribute with a complex array type (like the `issues` attribute in the `ListingsItemSubmissionResponse` response type), the code hits this block in `HasArrayableAttributes`:

https://github.com/jlevers/selling-partner-api/blob/f3ea73807bc45341bae14d38cccb7e11bc754ae5/src/Traits/HasArrayableAttributes.php#L72-L84

And that's what's happening for me, but for some reason it's not happening for you. Just to make extra sure, you're on the latest version of the library (`v7.3.1`)? I just don't want to push a fix for this before understanding why it's happening.

**Comment by GWTorstenDEV** [comment]
The error I mentioned has nothing to do with the call itself. Other calls also cause this PHP fatal error. Currently I get it with putListingsItem and patchListingsItem.

If you scroll up in this thread, you will see that the thread creater and others have the problem that the error message “..Uncaught Error: Call to a member function toArray() on array...” occurs when executing call `validateContentDocumentAsinRelations` and the scripts crashes.

System: PHP 8.3
Plugin v7.3.1
OS: AlmaLinux 9.5 (Teal Serval)

Regards
Torsten

**Comment by jlevers** [comment]
I understand that – it's just that no matter which call I use that is failing for other people, even if I send exactly the same request and get back exactly the same response, I don't encounter the error, and I'm trying to figure out what the difference is so that I can actually understand why the error is happening. I understand how the change you've shared fixes the problem, but I don't understand how you're ever landing on the problematic line of code in the first place in this scenario, since I'm not ever hitting the case that leads to it.
