### ISSUE TITLE
 After downloading the GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA report, a parsing error occurs.

### ISSUE THREAD

**Issue by BaiNight** [jlevers/selling-partner-api#809]
Version：v7.2.3

Download GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA with the following example code:
```
  use SellingPartnerApi\SellingPartnerApi;
  
  $reportType = 'GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA';
  $documentId = 'amzn1.spdoc.1.4.na....2610';
  
  $connector = SellingPartnerApi::seller(/* ... */);
  $response = $connector->reportsV20210630()->getReportDocument($documentId, $reportType);
  
  $reportDocument = $response->dto();
  
  $contents = $reportDocument->download($reportType);
```

After calling the: download method, an error occurs:：The conversion from Windows-1252 to UTF-8 failed. 

Call stack as follows：

#0 D:\php-project\amazon-api\vendor\openspout\openspout\src\Common\Helper\EncodingHelper.php(96): OpenSpout\Common\Helper\EncodingHelper->attemptConversion('Incorrect size,...', 'Windows-1252', 'UTF-8')
#1 D:\php-project\amazon-api\vendor\openspout\openspout\src\Reader\CSV\RowIterator.php(204): OpenSpout\Common\Helper\EncodingHelper->attemptConversionToUTF8('Incorrect size,...', 'Windows-1252')
#2 D:\php-project\amazon-api\vendor\openspout\openspout\src\Reader\CSV\RowIterator.php(132): OpenSpout\Reader\CSV\RowIterator->getNextUTF8EncodedRow()
#3 D:\php-project\amazon-api\vendor\openspout\openspout\src\Reader\CSV\RowIterator.php(90): OpenSpout\Reader\CSV\RowIterator->readDataForNextRow()
#4 D:\php-project\amazon-api\vendor\jlevers\selling-partner-api\src\Traits\DownloadsDocument.php(173): OpenSpout\Reader\CSV\RowIterator->next()
#5 D:\php-project\amazon-api\vendor\jlevers\selling-partner-api\src\Traits\DownloadsDocument.php(128): SellingPartnerApi\Seller\ReportsV20210630\Responses\ReportDocument->parseSpreadsheet('return-date\tord...')
#6 D:\php-project\amazon-api\vendor\jlevers\selling-partner-api\src\Traits\DownloadsDocument.php(84): SellingPartnerApi\Seller\ReportsV20210630\Responses\ReportDocument->parseDocument('return-date\tord...')
#7 D:\php-project\amazon-api\app\Http\Services\AmazonReportDocService.php(36): SellingPartnerApi\Seller\ReportsV20210630\Responses\ReportDocument->download('GET_FBA_FULFILL...')

**Comment by Uff182** [comment]
I'm stuck with the same problem for report GET_MERCHANT_LISTINGS_ALL_DATA.

The conversion from Windows-1252 to UTF-8 failed.
#0 /var/www/vhosts/mysite.it/dev8.mysite.it/amazonspapi/vendor/openspout/openspout/src/Common/Helper/EncodingHelper.php(96): OpenSpout\Common\Helper\EncodingHelper->attemptConversion()
#1 /var/www/vhosts/mysite.it/dev8.mysite.it/amazonspapi/vendor/openspout/openspout/src/Reader/CSV/RowIterator.php(204): OpenSpout\Common\Helper\EncodingHelper->attemptConversionToUTF8()
#2 /var/www/vhosts/mysite.it/dev8.mysite.it/amazonspapi/vendor/openspout/openspout/src/Reader/CSV/RowIterator.php(132): OpenSpout\Reader\CSV\RowIterator->getNextUTF8EncodedRow()
#3 /var/www/vhosts/mysite.it/dev8.mysite.it/amazonspapi/vendor/openspout/openspout/src/Reader/CSV/RowIterator.php(90): OpenSpout\Reader\CSV\RowIterator->readDataForNextRow()
#4 /var/www/vhosts/mysite.it/dev8.mysite.it/amazonspapi/vendor/jlevers/selling-partner-api/src/Traits/DownloadsDocument.php(173): OpenSpout\Reader\CSV\RowIterator->next()
#5 /var/www/vhosts/mysite.it/dev8.mysite.it/amazonspapi/vendor/jlevers/selling-partner-api/src/Traits/DownloadsDocument.php(128): SellingPartnerApi\Seller\ReportsV20210630\Responses\ReportDocument->parseSpreadsheet()
#6 /var/www/vhosts/mysite.it/dev8.mysite.it/amazonspapi/vendor/jlevers/selling-partner-api/src/Traits/DownloadsDocument.php(84): SellingPartnerApi\Seller\ReportsV20210630\Responses\ReportDocument->parseDocument()
#7 /var/www/vhosts/mysite.it/dev8.mysite.it/amazonspapi/inventoryreport.php(191): SellingPartnerApi\Seller\ReportsV20210630\Responses\ReportDocument->download()
#8 {main}

**Comment by emjay64** [comment]
Getting this with GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT from JP marketplace

Error during report processing: The conversion from CP932 to UTF-8 failed

**Comment by jlevers** [comment]
Do you know what the actual encoding of the original Amazon document should be? You can specify an encoding as a parameter to the `download()` method (docs [here](https://github.com/jlevers/selling-partner-api?tab=readme-ov-file#downloading-a-report-document)).

**Comment by emjay64** [comment]
I tried both
`$contents = $reportDocument->download($reportType, 'CP932');`
and 
`$contents = $reportDocument->download($reportType, 'UTF-8');`

getting the same result:
`The conversion from CP932 to UTF-8 failed`

**Comment by jlevers** [comment]
Have you tried using `Shift-JIS` instead of `CP932`? I think that's often the encoding that Amazon JP reports come in.

If that doesn't work, you can download the raw report data and parse it yourself by passing the `postProcess: false` argument to `download()`.

**Comment by 0xSekar** [comment]
We modified src/Traits/DownloadDocument.php on our server to fix this issue, but not sure if this will work for all cases:
1) At line 235 (based on current master) replaced `$encodings = [static::$defaultEncoding];` with `$encodings = [static::$defaultEncoding, 'CP932'];`
2) At line 232 replaced `array_unshift($encodings, $headerEncoding);` with `array_unshift($encodings, str_replace("Cp1252", "ISO-8859-1", $headerEncoding));`
3) At line 84 added `$this->encoding = static::$defaultEncoding;`

**Comment by emjay64** [comment]
@0xSekar Thanks! solved the issue, 
(correction:  1. should be **At line _225_** ....)

**Comment by 0xSekar** [comment]
> [@0xSekar](https://github.com/0xSekar) Thanks! solved the issue, (correction: 1. should be **At line _225_** ....)

Glad to hear and tanks for the correction. Fixed on the comment

**Comment by jlevers** [comment]
@0xSekar I would welcome a PR that packages up this fix into something reusable, if you'd be willing to make it :)
